openapi: 3.0.0
info:
  title: OBIE VRP Profile
  description: VRP swagger
  version: 1.0.0-draft1
tags:
  - name: variable-recurring-payments
paths:
  /domestic-vrp-consents:
    post:
      tags:
        - variable-recurring-payments
      summary: create a domestic vrp
      description: create a domestic vrp
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OBDomesticVRPConsentResponse'

  /domestic-vrp-consents/:consentId:
    get:
      tags:
        - variable-recurring-payments
      summary: create a domestic vrp
      description: create a domestic vrp
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OBDomesticVRPConsentResponse'

    delete:
      tags:
        - variable-recurring-payments
      summary: create a domestic vrp
      description: create a domestic vrp
      responses:
        '204':
          description: 'all good'

  /domestic-vrp-consents/:consentId/funds-confirmation:
    post:
      tags:
        - variable-recurring-payments
      summary: create a domestic vrp
      description: create a domestic vrp
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#components/schemas/OBVRPFundsConfirmationResponse'

components:
  schemas:
    OBDomesticVRPConsentResponse:
      type: object
      required:
        - Data
        - Risk
        - Links
        - Meta

      properties:
        Data:
          type: object
          required:
            - ConsentId
            - CreationDateTime
            - Status
            - StatusUpdateDateTime
            - ControlParameters
            - Initiation
            - DebtorAccount
          properties:
            ConsentId:
              type: string              
              description: >
                Unique identification as assigned by the ASPSP to uniquely identify the consent resource.      | Max128Text
            CreationDateTime:
              type: string
              format: date-time
              description: >
                Date and time at which the resource was created.|ISODateTime
            Status:
              type: string
              description: >
                Specifies the status of resource in code form.  |Authorised AwaitingAuthorisation Rejected Revoked Expired
            StatusUpdateDateTime:
              type: string
              format: date-time
              description: >
                Date and time at which the resource status was updated.  | ISODateTime  
            ControlParameters:
              $ref: '#/components/schemas/OBDomesticVRPControlParameters'
            Initiation:
              $ref: '#/components/schemas/OBDomesticVRPInitiation'
            DebtorAccount:
              $ref: '#/components/schemas/OBCashAccountDebtorWithName'
        Risk:
          $ref: '#/components/schemas/OBRisk1'
        Links:
          $ref: '#/components/schemas/Links'
        Meta:
          $ref: '#/components/schemas/Meta'

    OBDomesticVRPConsentRequest:
      type: object
      required:
        - Data
        - Risk
      properties:
        Data:
          type: object
          required: 
            - ControlParameters
            - Initiation

          properties:
            ControlParameters:
              $ref: '#/components/schemas/OBDomesticVRPControlParameters'
            Initiation:
              $ref: '#/components/schemas/OBDomesticVRPInitiation'
        Risk:
          $ref: '#/components/schemas/OBRisk1'

    OBDomesticVRPControlParameters:
      type: object
      required:
        - VRPType

      properties:
        ValidFromDateTime:
          type: string
          format: date-time
          description: ^
            Start date time for which the consent remains valid. | ISODateTime
        ValidToDateTime:
          type: string
          format: date-time
          description: ^
            End date time for which the consent remains valid. | ISODateTime
        Reference:
          type: string
          maxLength: 35
          description: ^
            Unique reference, as assigned by the creditor, to unambiguously refer to the consent.     | Max35Text  
        MaximumIndividualAmount:
          type: object
          required:
            - Amount
            - Currency
          properties:
            Amount:
              type: string
              description: ^
                A number of monetary units specified in an active currency where the unit of currency is explicit and compliant with ISO 4217.
            Currency:
              type: string
              description: ^
                A code allocated to a currency by a Maintenance Agency under an international identification scheme, as described in the latest edition of the international standard ISO 4217 "Codes for the representation of currencies and funds".   | ActiveOrHistoricCurrencyCode  
        MaximumMonthlyAmount:
          type: object
          required:
            - Amount
            - Currency
          properties:
            Amount:
              type: string
              description: ^
                A number of monetary units specified in an active currency where the unit of currency is explicit and compliant with ISO 4217.
            Currency:
              type: string
              description: ^
                A code allocated to a currency by a Maintenance Agency under an international identification scheme, as described in the latest edition of the international standard ISO 4217 "Codes for the representation of currencies and funds".   | ActiveOrHistoricCurrencyCode          
        VRPType:
          type: string
          description: ^
            The types of payments that can be made under this VRP consent. This can be used to indicate whether this include sweeping payment or other ecommerce payments. A value of `UK.OBIE.VRPType.Sweeping` can only be used when the API is called with the `vrp-consents:sweeping` scope. A value of `UK.OBIE.VRPType.Other` can only be used when the API is called with teh `vrp-consents:other` scope. | OBVRPConsentType - Namespaced Enumeration

    OBDomesticVRPInitiation:
      type: object
      properties:
        DebtorAccount:
          $ref: '#/components/schemas/OBCashAccountDebtorWithName'
        CreditorAgent:
          $ref: '#/components/schemas/OBBranchAndFinancialInstitutionIdentification6'
        CreditorAccount:
          $ref: '#/components/schemas/OBCashAccountCreditor3'

    OBCashAccountDebtorWithName:
      type: object
      required:
        - SchemeName
        - Identification
        - Name
      properties:
        SchemeName:
          type: string
          description: ^
            Name of the identification scheme, in a coded form as published in an external list. | Namespaced Enumeration OBExternalAccountIdentification4Code
        Identification:
          type: string
          description: ^
            Identification assigned by an institution to identify an account. This identification is known by the account owner. | Max256Text
        Name:
          type: string
          description: ^
            Name of the account, as assigned by the account servicing institution.  Usage The account name is the name or names of the account owner(s) represented at an account level. The account name is not the product name or the nickname of the account.
        SecondaryIdentification:
          type: string
          description: ^
            This is secondary identification of the account, as assigned by the account servicing institution.  This can be used by building societies to additionally identify accounts with a roll number (in addition to a sort code and account number combination) | Max34Text

    OBCashAccountCreditor3:
      type: object
      required:
        - SchemeName
        - Identification
        - Name
      properties:
        SchemeName:
          type: string
          description: ^
            Name of the identification scheme, in a coded form as published in an external list. | Namespaced Enumeration OBExternalAccountIdentification4Code
        Identification:
          type: string
          description: ^
            Identification assigned by an institution to identify an account. This identification is known by the account owner. | Max256Text
        Name:
          type: string
          description: ^
            Name of the account, as assigned by the account servicing institution.  Usage The account name is the name or names of the account owner(s) represented at an account level. The account name is not the product name or the nickname of the account.
        SecondaryIdentification:
          type: string
          description: ^
            This is secondary identification of the account, as assigned by the account servicing institution.  This can be used by building societies to additionally identify accounts with a roll number (in addition to a sort code and account number combination) | Max34Text

    OBBranchAndFinancialInstitutionIdentification6:
      type: object
      properties:
        SchemeName:
          type: string
          description: ^
            0..1) | `SchemeName` |Name of the identification scheme, in a coded form as published in an external list. |OBExternalFinancialInstitutionIdentification4Code
        Identification:
          type: string
          description: ^
            0..1) | `Identification` |Unique and unambiguous identification of a financial institution or a branch of a financial institution.  | Max35Text  
        Name:
          type: string
          description: ^
            0..1) | `Name` | Name by which an agent is known and which is usually used to identify that agent. | Max140Text
        PostalAddress:
          type: object
          description: ^
            0..1) | `PostalAddress` |Information that locates and identifies a specific address, as defined by postal services.| OBPostalAddress6
          properties:            
            AddressType:
              type: string
              description: ^
                0..1) | `PostalAddress. AddressType` |Identifies the nature of the postal address. |OBAddressTypeCode  |Business Correspondence DeliveryTo MailTo POBox Postal Residential Statement
            Department:
              type: string
              description: ^
                0..1) | `PostalAddress. Department` |Identification of a division of a large organisation or building. | Max70Text  
            SubDepartment:
              type: string
              description: ^
                0..1) | `PostalAddress. SubDepartment` |Identification of a sub-division of a large organisation or building. |Max70Text
            StreetName:
              type: string
              description: ^
                0..1) | `PostalAddress. StreetName`   |Name of a street or thoroughfare.    |Max70Text  
            BuildingNumber:
              type: string
              description: ^
                0..1) | `PostalAddress. BuildingNumber` |Number that identifies the position of a building on a street.   |Max16Text  
            PostCode:
              type: string
              description: ^
                0..1) | `PostalAddress. PostCode` |Identifier consisting of a group of letters and. or numbers that is added to a postal address to assist the sorting of mail.    |Max16Text  
            TownName:
              type: string
              description: ^
                0..1) | `PostalAddress. TownName` |Name of a built-up area, with defined boundaries, and a local government. |Max35Text  
            CountrySubDivision:
              type: string
              description: ^
                0..1) | `PostalAddress. CountrySubDivision` |Identifies a subdivision of a country such as state, region, county.      |Max35Text  
            Country:
              type: string
              description: ^
                0..1) | `PostalAddress. Country` | Nation with its own government.      |CountryCode
            AddressLine:
              type: array
              items:
                type: string



    OBRisk1:
      type: object
      properties:
        PaymentContextCode:
          type: string
          description: Specifies the payment context
          enum:
          - BillPayment
          - EcommerceGoods
          - EcommerceServices
          - Other
          - PartyToParty
        MerchantCategoryCode:
          maxLength: 4
          minLength: 3
          type: string
          description: Category code conform to ISO 18245, related to the type of
            services or goods the merchant provides for the transaction.
        MerchantCustomerIdentification:
          maxLength: 70
          minLength: 1
          type: string
          description: The unique customer identifier of the PSU with the merchant.
        DeliveryAddress:
          required:
          - Country
          - TownName
          type: object
          properties:
            AddressLine:
              maxItems: 2
              minItems: 0
              type: array
              items:
                maxLength: 70
                minLength: 1
                type: string
                description: Information that locates and identifies a specific address,
                  as defined by postal services, that is presented in free format
                  text.
            StreetName:
              $ref: '#/components/schemas/StreetName'
            BuildingNumber:
              $ref: '#/components/schemas/BuildingNumber'
            PostCode:
              $ref: '#/components/schemas/PostCode'
            TownName:
              $ref: '#/components/schemas/TownName'
            CountrySubDivision:
              $ref: '#/components/schemas/CountrySubDivision'
            Country:
              pattern: ^[A-Z]{2,2}$
              type: string
              description: Nation with its own government, occupying a particular
                territory.
          description: Information that locates and identifies a specific address,
            as defined by postal services or in free format text.
      description: The Risk section is sent by the initiating party to the ASPSP.
        It is used to specify additional details for risk scoring for Payments.
    StreetName:
      maxLength: 70
      minLength: 1
      type: string
      description: Name of a street or thoroughfare.
    TownName:
      maxLength: 35
      minLength: 1
      type: string
      description: Name of a built-up area, with defined boundaries, and a local government.
    PostCode:
      maxLength: 16
      minLength: 1
      type: string
      description: Identifier consisting of a group of letters and/or numbers that
        is added to a postal address to assist the sorting of mail.
    BuildingNumber:
      maxLength: 16
      minLength: 1
      type: string
      description: Number that identifies the position of a building on a street.
    CountrySubDivision:
      maxLength: 35
      minLength: 1
      type: string
      description: Identifies a subdivision of a country such as state, region, county.

    Links:
      required:
      - Self
      type: object
      properties:
        Self:
          type: string
          format: uri
        First:
          type: string
          format: uri
        Prev:
          type: string
          format: uri
        Next:
          type: string
          format: uri
        Last:
          type: string
          format: uri
      description: Links relevant to the payload
    Meta:
      title: MetaData
      type: object
      properties:
        TotalPages:
          type: integer
          format: int32
        FirstAvailableDateTime:
          type: string
          format: date-time
        LastAvailableDateTime:
          type: string
          format: date-time
      description: Meta Data relevant to the payload
  


  securitySchemes:
    TPPOAuth2Security:
      type: oauth2
      description: TPP client credential authorisation flow with the ASPSP
      flows:
        clientCredentials:
          tokenUrl: https://authserver.example/token
          scopes:
            payments: Generic payment scope
    PSUOAuth2Security:
      type: oauth2
      description: OAuth flow, it is required when the PSU needs to perform SCA with
        the ASPSP when a TPP wants to access an ASPSP resource owned by the PSU
      flows:
        authorizationCode:
          authorizationUrl: https://authserver.example/authorization
          tokenUrl: https://authserver.example/token
          scopes:
            payments: Generic payment scope
            